spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/notification
    username: postgres
    password: root
    driver-class-name: org.postgresql.Driver
  jpa:
    properties:
      hibernate:
        generate_statistics: true
        jdbc:
          batch_size: 500
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
  kafka:
    bootstrap-servers: 127.0.0.1:9092

#TODO: remove port
server:
  port: 8081

replication:
  consume:
    topic:
      geofence: geofence-sync
